redis:
  url: '127.0.0.1'
  port: 6379
  password: 'a12345'
  db: 3
  expiration: 0
registeredPath: "/api/register"
remote:
  startInit: false
  name: aliyun.dcs
  url: http://127.0.0.1:8081
  destinations: "http://127.0.0.1:22699"
local:
  startInit: false
  name: aliyun.dcs
  url: http://127.0.0.1:8081
  destinations: "http://127.0.0.1:8081"
